/*
  Project name    : UPSShutdownWatcher
  Description     : Auto shutdown Android after signal
  Author          : Dangelo Brusorio (dangelo@brusorio.nl)
  Date            : 2022-07-27
  Version         : 0.1
  Based on        : https://juice4halt.com/download
*/
/*
  POSSIBLE USAGE: ./UPSShutdownWatcher; if [ $? -eq 0 ]; then reboot -p; fi
*/
#include <sys/stat.h>
#include <sys/types.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include "GPIO.h"

#define COMMUNICATION_SIGNAL_GPIO 25 /* Pin-22 */

int
main(int argc, char *argv[])
{
	/*
	 * Create directory for working with COMMUNICATION_SIGNAL_GPIO and wait
	 */
	if (-1 == GPIOExport(COMMUNICATION_SIGNAL_GPIO))
		return(1);

	/*
	 * Set COMMUNICATION_SIGNAL_GPIO as output and set output to LOW
	 */
	if (-1 == GPIODirection(COMMUNICATION_SIGNAL_GPIO, OUT))
		return(1);

  if (-1 == GPIOWrite(COMMUNICATION_SIGNAL_GPIO, LOW))
		return(1);

  usleep(100 * 1000);

  if (-1 == GPIODirection(COMMUNICATION_SIGNAL_GPIO, IN))
		return(1);

  /*
	 * Wait until pin rises to HI
	 */
  usleep(100 * 1000);

  int GPIO_READING_1 = 1;
  int GPIO_READING_2 = 1;
  int COUNT = 1;

  /*
   * To be resistant to short pulses (e.g. 100ms pulse generated by the rebootj4h script) two readings 200ms apart from each other are required
   */
  while (COUNT < 3) {
    printf("Scanning for power loss...\n");
    ++COUNT;
    GPIO_READING_1 = GPIORead(COMMUNICATION_SIGNAL_GPIO);

    usleep(200 * 1000);

    GPIO_READING_2 = GPIORead(COMMUNICATION_SIGNAL_GPIO);

    if (GPIO_READING_1 == 0 && GPIO_READING_2 == 0)
      break;
  }
	
  /*
	 * Set COMMUNICATION_SIGNAL_GPIO as output and set output to LOW
	 */
  if (-1 == GPIODirection(COMMUNICATION_SIGNAL_GPIO, OUT))
    return(1);

  if (-1 == GPIOWrite(COMMUNICATION_SIGNAL_GPIO, LOW))
		return(1);

  printf("Shutting down!\n");

	return(0);
}